✨ Add coherent artifact plot functionality
glotaran/pyglotaran-extras pull request #123
Opened 2022-12-29 20:09 UTC by s-weigand

This change adds a new plot function `plot_coherent_artifact` which implements #33.

Here are some example plots for the [DOAS example](https://github.com/glotaran/pyglotaran-examples/tree/main/pyglotaran_examples/ex_doas_beta) (currently our own example that uses the coherent artifact):
![image](https://user-images.githubusercontent.com/9513634/210006319-a8ba68da-aa2c-4aa6-9c19-3d44a3274f01.png)
![image](https://user-images.githubusercontent.com/9513634/210006360-56c22a47-82bc-4bc2-90f0-8033281f5419.png)

### Change summary

- :sparkles: [ Added abs_max helper function](https://github.com/glotaran/pyglotaran-extras/commit/de7bd7a0051c62c0bd4d12d8e20db1720ffba7b8)
- :recycle: [ Refactored add_cycler_if_not_none to also work on multiple axes](https://github.com/glotaran/pyglotaran-extras/commit/f38fbf855c62612dfcd8bfe7d9a2c4b1a1b2af04)
- :sparkles: [ Added plot_coherent_artifact function](https://github.com/glotaran/pyglotaran-extras/commit/9631fa17f028c340b8f448f9d855d10fd5aaae85)

### Checklist

- [ ] ✔️ Passing the tests (mandatory for all PR's)
- [x] 🧪 Adds new tests for the feature (mandatory for ✨ feature and 🩹 bug fix PR's)

### Closes issues

Not sure for which other plots #33 applies, so we might want to factor out the scaling and normalization into another helper function thus I'm not marking it as closed.

2022-12-29 20:20 UTC, jsnel requested changes
Looks good, corrected some small imperfections in doc strings.

2022-12-29 20:20 UTC, jsnel commented on pyglotaran_extras/plotting/plot_coherent_artifact.py
> +        plot this value does not need to be an exact existing value and only has a effect if the
```suggestion
        plot this value does not need to be an exact existing value and only has effect if the
```

2022-12-29 20:20 UTC, jsnel commented on pyglotaran_extras/plotting/plot_coherent_artifact.py
> +        Whether or not to normalize the IRF derivative plot.If the IRF derivative is normalized,
```suggestion
        Whether or not to normalize the IRF derivative plot. If the IRF derivative is normalized,
```

2022-12-29 20:20 UTC, jsnel commented on pyglotaran_extras/plotting/plot_coherent_artifact.py
> +        Size of the figure (N, M) in inches. Defaults to (18, 7)
```suggestion
        Size of the figure (N, M) in inches. Defaults to (18, 7).
```

2022-12-29 20:20 UTC, jsnel commented on pyglotaran_extras/plotting/plot_coherent_artifact.py
> +        the full time range is used
```suggestion
        the full time range is used.
```

2022-12-29 20:20 UTC, jsnel commented on pyglotaran_extras/plotting/utils.py
> +        Defaults to () which results in the absolute maximum of all values
```suggestion
        Defaults to () which results in using the absolute maximum of all values.
```

2022-12-30 08:59 UTC, ism200 reviewed
thanks a lot sebastian. this function is key to the Lego-paper. indeed (the concept of) this function should also work with different input, e.g. concentrations and SA(D)S, or damped oscillations and DOAS. let us give that a try when we zoom again. if indeed we can generalize, then the name can become more generic. we will of course then need arguments to indicate what we want to plot. i foresee now three types of input: (1) IRF derivatives and IRFAS, (2) damped oscillations and DOAS, (3) concentrations and SA(D)S. Since these are all fixed pairs, one named arguments suffices.

2023-01-01 23:07 UTC, s-weigand commented
Since factoring out the scaling would be just an internal change and affect the user facing API this could be done in a l8er PR.

2023-01-01 23:52 UTC, jsnel approved these changes

2023-01-01 23:53 UTC, merged